fix: website accessibility fixes
vmware/clarity pull request #5087
Opened 2020-09-28 20:49 UTC by hippee-lee

- update image labels for app-layout images
- fixes for icon buttons
- properly label getting started intro for supported browsers image

Signed-off-by: Matt Hippely <mhippely@vmware.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?
Adds more accessible behavior to website content.

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Adds more accessible behavior to website content.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-09-28 21:23 UTC, mathisscott requested changes

2020-09-28 21:23 UTC, mathisscott commented on apps/website/get-started/README.md
> +<ClrImage src="/images/get-started/device_support.png" width="100%" aria-label="Image showing supported browser list that container icons for: IE11, Edge, Chrome, Safari and Firefox."/>
I think this is supposed to say `that contains icons for: ` instead of `that container icons for:`

2020-09-29 01:31 UTC, mathisscott approved these changes

2020-09-30 08:24 UTC, bbogdanov commented
@hippee-lee I have some code for solving other issues, so would you like to push my code into your branch and get all the fixes we have at once?

2020-09-30 08:25 UTC, bbogdanov commented
Seems also like the file we had with the issue is not much of a great way to track what we do because we did a double work here

2020-09-30 15:40 UTC, hippee-lee commented
> @hippee-lee I have some code for solving other issues, so would you like to push my code into your branch and get all the fixes we have at once?

Let's keep the changes separate. If the code is changes in a similar way it will just rebase overtop but if they are different we can discuss that on the new PR.

Sorry about the confusion - perhaps the spreadsheet is not updating?

2020-09-30 15:53 UTC, bbogdanov approved these changes

2020-09-30 15:54 UTC, merged