fix(datagrid): add aria-label to string filter input
vmware/clarity pull request #5131
Opened 2020-10-09 04:22 UTC by amellnik

Add a new common string for "Search" and use it to add an aria-label to the datagrid default string filter input.  This string can probably be used elsewhere in the future.

Partially closes: #4756

Signed-off-by: Alex Mellnik <a.r.mellnik@gmail.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The datagrid default string filter does not have an aria-label or placeholder.  

Issue Number: #4986 

## What is the new behavior?

This adds the aria label via a new common string.  It doesn't populate the placeholder but that would be easy to do.  

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2020-10-09 13:50 UTC, bdryanovski requested changes
You gonna need to update the `clr-angular.d.ts` file by running 

```bash
$ cd packages/angular
$ yarn golden:fix
```
To fix the issue with the failing test.

Also a unit-test will be nice to cover the use of the new `attr.aria-label` and the use of `commonStrings.keys.search`

2020-10-09 18:25 UTC, gnomeontherun commented
I'm not opposed to this, but it doesn't really solve the need that we have for the labels to be fully descriptive. Just 'Search' is not helpful for screen readers and we need to come up with a solution that allows for customized labels per use. 

Tagging @chlane and @scroniser for visibility.

2020-10-09 19:58 UTC, chlane commented
@gnomeontherun Agreed, the label should say what is being searched. That content should come from the Clarity consumer.

2020-10-09 22:27 UTC, hippee-lee commented
Hi @amellnik - fyi we changed the default branch for the Clarity repo to `next`. 
I updated this pull request for the new default branch. Please reach out if you run into any issues.

Thanks for another contribution!!

2020-10-10 03:27 UTC, amellnik commented
Should we add this as the default behavior and add an @Input to for the user to override the placeholder text?  Is there a better default phrase that we should use than just "Search"?  The numeric filter currently has "Min value" and "Max value" for placeholders.

2020-10-11 05:00 UTC, amellnik commented
I had a really hard time getting this to build, it turned out that I needed to delete my local copy, reclone, `yarn install` and then run `golden:fix` prior to running any build steps in order to get it to work, not sure why.  

Added a test for the `aria-label`, waiting on feedback on:
* Adding a placeholder to go with the aria-label
* Adding an `@Input` so downstream users can override it
* Change `Search` to something else, maybe `Filter` or something?

2020-10-12 05:54 UTC, bdryanovski requested changes
Thanks, @amellnik for the contribution, 

I didn't find anywhere the `@Input` change that you mention - or this is no longer relevant? 

I have few minnor changes to add.

Like @gnomeontherun mention, the `search` key is not that well named and may point people in the wrong direction. In this case, we are opening filter so maybe the default text must be something close to `Filter items` then `Search`.

In the current version of the `fix` changing the `CommonStrings` value, it will affect every Datagrid and Filter at the same time. As developers, we could provide additional information for example `Filter users by there first name` (maybe over-kill). So for doing this we gonna need some way to pass this value `@Input` is an option.  And still have some default value for the cases that we can't or we don't want to provide additional information.

2020-10-12 16:53 UTC, amellnik commented
Hi @bdryanovski,

I didn't add the @Input in the first pass, but will do so now if we're ok with that approach.  I'll also mention and show it in the documentation.  `Filter items` does seem clearer, I'll update the default string to that.

2020-10-13 17:21 UTC, gnomeontherun commented
I don't want to add a new @Input for the override string, we need a different pattern but that is beyond the scope of this PR. I think we can focus on just having it use the global string and worry about the localized override later.

2020-10-14 03:57 UTC, amellnik commented
Updated to use "Filter items" for the aria-label.  This is still not populating a placeholder but that could easily be added if we want.

2020-10-27 01:01 UTC, amellnik commented
As per Jeremy, not adding an `@Input` for now.

2020-10-27 05:48 UTC, bdryanovski approved these changes

2020-10-28 02:03 UTC, amellnik commented
If you found this helpful I'd appreciate it if you would add the hacktoberfest-accepted -- I'm attempting to mine a shirt. Cheers -A

2020-10-29 23:02 UTC, gnomeontherun approved these changes

2020-10-29 23:11 UTC, merged