docs: update icon page with cds-icon usage
vmware/clarity pull request #5330
Opened 2020-11-24 11:09 UTC by bbogdanov

Updating the icons page to reflect our icon usage from versions >4.x.x

Signed-off-by: Bogdan Bogdanov <bbogdanov@vmware.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-11-24 11:10 UTC, bbogdanov commented on apps/website/foundation/icons/api.md
> +permalink: /storybook/core/?path=/story/components-icon-getting-started--page
Little hack that can be used to redirect the user to storybook when the origin of the website is `clarity.design`

2020-12-01 13:45 UTC, bbogdanov commented
@hippee-lee Is this PR needed after the improvements you share for the website content yesterday?

2020-12-01 16:34 UTC, hippee-lee requested changes
This change should go into the the [core documentation branch](https://github.com/vmware/clarity/tree/topic/website-core-docs) (for v5).

We don't want to mix core docs with the older ones.

2020-12-01 16:34 UTC, hippee-lee commented on apps/website/foundation/icons/api.md
> +[Go to Storybook](https://clarity.design/storybook/core/?path=/story/components-icon-getting-started--page)
Instead of linking to the storybook page this should be updated / editied to include relevant info from the storybook docs.

2020-12-04 00:12 UTC, Shijir requested changes

2020-12-04 00:12 UTC, Shijir commented on apps/website/foundation/icons/usage.md
> +<clr-icon shape="caret" style="transform: rotate(0deg);"></cds-icon>
clr?

2020-12-04 00:12 UTC, Shijir commented on apps/website/foundation/icons/usage.md
> +<!--A. SETTING THE ROTATION DIRECTION THROUGH CLR-ICON DIRECTION ATTRIBUTE-->
This comment is visible in examples, right? Then, we might want to change CLR to CDS.

2020-12-04 05:36 UTC, closed without merging