feat: allow env flag set for core logging
vmware/clarity pull request #5389
Opened 2020-12-15 21:40 UTC by coryrylan

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the new behavior?
This is a small feature that allows a production env flag to be set on the global CDS object so teams can disable our dev time specific logging. The logs can create a lot of noise in a production environment when logs are recorded. This would allow teams to disable when deploying their applications similar to Angular.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-12-15 23:11 UTC, mathisscott requested changes

2020-12-15 23:11 UTC, mathisscott commented on packages/core/src/internal/utils/global.ts
> +  _react: { version: string }; // set by @cdr/react
`@cds` not `@cdr`

2020-12-15 23:56 UTC, hippee-lee approved these changes

2020-12-16 17:33 UTC, bbogdanov approved these changes

2020-12-16 21:47 UTC, mathisscott approved these changes

2020-12-17 16:44 UTC, merged