docs: re-work foundation pages
vmware/clarity pull request #5414
Opened 2020-12-23 23:51 UTC by hippee-lee

- move app-layout into angular components
- add layouts content overview, vertical, horizontal, grid and utils
- add design tokens content
- adds a web-component for the website `token-table` and port functions from storybook for generating token metadata

0. create foundation content for interaction styles
1. token table css isn't working
2. token table template needs responsiveness
3. i18n content needs updated w for core but not enough ins in storybook so need to use it so I can write it
4. typography content needs to be updated for core with the token-table metadata. What to do with the angular specific stuff - keep and moce or toss it?
5. design updates (in Figma) for form controls
6. Navigation content - update for core? move ng specific? toss?

Signed-off-by: Matt Hippely <mhippely@vmware.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2021-01-04 06:51 UTC, bbogdanov approved these changes

2021-01-04 08:17 UTC, bdryanovski approved these changes
LGTM

2021-01-04 15:51 UTC, mathisscott requested changes

2021-01-04 15:51 UTC, mathisscott commented on apps/website/foundation/layouts/utilities.md
> +Screen Reader Only
No header level here? I would expect `##` or `###`

2021-01-11 19:21 UTC, hippee-lee commented on apps/website/foundation/layouts/utilities.md
> +Screen Reader Only
Too much egg nog 😝 ...

2021-01-11 23:54 UTC, hippee-lee commented
Closing this as a POC instead of a proposed change for the v5 release. 
I'll keep the branch so it could be used as a starting point if needed later on.

2021-01-11 23:54 UTC, closed without merging