docs: update main README.md
vmware/clarity pull request #5422
Opened 2021-01-05 08:30 UTC by bbogdanov

Updating the main README.md to incoming v5 changes.

Signed-off-by: Bogdan Bogdanov <bbogdanov@vmware.com>

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-01-05 09:20 UTC, bdryanovski requested changes
Small changes related to the badges and build status

2021-01-05 09:20 UTC, bdryanovski commented on README.md
> +| [![Build Status](https://travis-ci.com/vmware/clarity.svg?branch=master)](https://travis-ci.com/vmware/clarity) | [![npm version](https://badge.fury.io/js/%40clr%2Fcore.svg)](https://badge.fury.io/
I think that these build/package icons are not valid anymore.

* We don't use Travis CI for a long time so we need to update them with the Github Action more [here](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/adding-a-workflow-status-badge)
* NPM Version badge is targeting `clr/core` package that is not the only package that we have. So adding other packages will be a best


![npm version core](https://img.shields.io/npm/v/@cds/core/latest?label=%40cds%2Fcore&style=flat-square)
![npm version angular](https://img.shields.io/npm/v/@clr/angular/latest?label=%40clr%2Fangular&style=flat-square)
![npm version cds angular](https://img.shields.io/npm/v/@cds/angular/latest?label=%40cds%2Fangular&style=flat-square) - when released
![npm version ui](https://img.shields.io/npm/v/@clr/ui/latest?label=%40clr%2Fui&style=flat-square)
![npm version icons](https://img.shields.io/npm/v/@clr/icons/latest?label=%40clr%2Ficons&style=flat-square)

```
![npm version icons](https://img.shields.io/npm/v/@clr/icons/latest?label=%40clr%2Ficons&style=flat-square)
```

2021-01-06 08:31 UTC, bdryanovski approved these changes

2021-01-11 23:51 UTC, hippee-lee approved these changes

2021-01-13 12:48 UTC, bbogdanov commented
@gnomeontherun let me know when I can merge this one

2021-01-26 19:55 UTC, mathisscott commented
@bbogdanov : Is this going to be merged?

2021-01-26 20:09 UTC, bbogdanov commented
Waiting @gnomeontherun for confirmation cause he had some improvement suggestions last time we spoke about this PR

2021-01-26 21:58 UTC, gnomeontherun commented
I don't remember what I was going to say, so 👍

2021-01-27 07:22 UTC, merged