docs: update layout content in form components
vmware/clarity pull request #5453
Opened 2021-01-15 20:12 UTC by Shijir

Signed-off-by: stsogoo <stsogoo@vmware.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-01-15 21:51 UTC, hippee-lee approved these changes

2021-01-15 23:48 UTC, mathisscott requested changes

2021-01-15 23:48 UTC, mathisscott commented on apps/website/core-components/file/README.md
> +Files are available in vertical, horizontal, and compact layout. See more layout guidelines on the [form page](/web-components/form/).
`File inputs` instead of `Files`?

2021-01-15 23:48 UTC, mathisscott commented on apps/website/core-components/input/README.md
> +Inputs are available in vertical, horizontal, compact, and controled-width layout. Controled-width layout is an additional option for setting the width in cases where the control may be unattractive
`controlled-width` not `controled-width`

2021-01-15 23:48 UTC, mathisscott commented on apps/website/core-components/range/README.md
> +Range are available in vertical, horizontal, and compact layout. See more layout guidelines on the [form page](/web-components/form/).
`Range inputs` not `range`

2021-01-15 23:48 UTC, mathisscott commented on apps/website/core-components/search/README.md
> +Search is available in vertical, horizontal, and compact layout. Horizontal layouts are preferred when it is often used on its own in a horizontal container such as an application header. See more la
`Search inputs are` not `Search is`

2021-01-15 23:48 UTC, mathisscott commented on apps/website/core-components/select/README.md
> +Select is available in vertical, horizontal, compact, and multiple layout. The select multiple option enables to user to select and view several items at once. See more layout guidelines on the [form
`Select elements are` not `Select is`

`Select elements with the multiple attribute` not `The select multiple option`

`enables the user` not `enables to user`

2021-01-15 23:48 UTC, mathisscott commented on apps/website/core-components/toggle/README.md
> +Toggle is available in vertical, vertical inline, horizontal, horizontal inline, compact layout. The align options for Toggle are useful for creating continuity with other UI elements that are relate
`horizontal, horizontal inline, and compact layout` not `horizontal, horizontal inline, compact layout`

2021-01-16 01:22 UTC, mathisscott approved these changes

2021-01-16 03:47 UTC, merged