feat: add ESLint rules warning against the usage of @clr/angular components
vmware/clarity pull request #5610
Opened 2021-02-16 14:31 UTC by sis0k0

## Rules

This PR adds the following rules to the `@clr/eslint-plugin-clarity-adoption` package:

- `no-clr-datalist`
- `no-clr-form`
- `no-clr-input`
- `no-clr-list`
- `no-clr-modal`
- `no-clr-password`
- `no-clr-radio`
- `no-clr-range`
- `no-clr-select`
- `no-clr-textarea`
- `no-clr-toggle`

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

Issue Number: #5528

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

2021-02-16 19:10 UTC, mathisscott requested changes

2021-02-16 19:10 UTC, mathisscott commented on packages/eslint-plugin-clarity-adoption/docs/rules/no-clr-modal.md
> +The use of Clarity Angular list is discouraged. Use Clarity Core list instead.
Lines 1-3 say "list" but the code examples show modals...

2021-02-17 06:21 UTC, sis0k0 commented on packages/eslint-plugin-clarity-adoption/docs/rules/no-clr-modal.md
> +The use of Clarity Angular list is discouraged. Use Clarity Core list instead.
I'll fix that and double-check the other components for similar mistakes.

2021-02-17 16:14 UTC, mathisscott approved these changes

2021-02-17 18:17 UTC, coryrylan commented on packages/eslint-plugin-clarity-adoption/docs/rules/no-clr-input.md
> +</cds-input-group>
`cds-input-group` is only required when using 2 or more inputs as a single inline input.

https://clarity.design/storybook/core/?path=/story/forms-input-groups--page

2021-02-17 18:20 UTC, coryrylan approved these changes

2021-02-17 18:26 UTC, hippee-lee approved these changes

2021-02-17 20:06 UTC, merged