chore: adding visual improvements and two components to adoption guide
vmware/clarity pull request #5686
Opened 2021-03-05 10:09 UTC by bbogdanov

Signed-off-by: Bogdan Bogdanov <bbogdanov@vmware.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [x] Other... Please describe:

Adoption guide

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-03-05 22:55 UTC, mathisscott requested changes

2021-03-05 22:55 UTC, mathisscott commented on packages/angular/projects/clarity-adoption/src/app/app.component.html
> +      <a cds-layout="m-x:md" routerLink="/" class="nav-link"><span class="title">Clarity Adoption</span></a>
🏆

2021-03-05 22:55 UTC, mathisscott commented on packages/angular/projects/clarity-adoption/src/app/app.component.html
> +      <cds-divider cds-layout="m-y:md"></cds-divider>
🙌

2021-03-05 22:55 UTC, mathisscott commented on packages/angular/projects/clarity-adoption/src/app/pages/accordion/accordion.page.html
> +  There is <b>eslint plugin</b> that could help with the adoption of Core Alerts. By locating and pinpoint the places
`There is an...`

`...the adoption of Core Accordions.`

`By locating and pinpointing...`

2021-03-05 22:55 UTC, mathisscott commented on packages/angular/projects/clarity-adoption/src/app/pages/checkbox/checkbox.page.html
> +  There is <b>eslint plugin</b> that could help with the adoption of Core Alerts. By locating and pinpoint the places
`There is an...`

`...with the adoption of Core Checkboxes.`

`By locating and pinpointing...`

2021-03-05 22:55 UTC, mathisscott commented on packages/angular/projects/clarity-adoption/src/app/pages/checkbox/checkbox.page.ts
> +    // {
Big commented out stuff still needed?

2021-03-08 15:45 UTC, mathisscott approved these changes

2021-03-08 16:19 UTC, sis0k0 approved these changes

2021-03-08 17:55 UTC, merged