fix: core icon render performance
vmware/clarity pull request #5690
Opened 2021-03-05 20:29 UTC by coryrylan

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

When rendering icons it can cause unnecessary render calculations for size causing performance slow down.

Before:
<img width="1653" alt="before" src="https://user-images.githubusercontent.com/2021067/110169926-0588a980-7dbf-11eb-8f5d-c84a79571a54.png">

After:
<img width="1610" alt="after" src="https://user-images.githubusercontent.com/2021067/110169932-07eb0380-7dbf-11eb-9c3a-1ddff78590bf.png">

## What is the new behavior?
This PR prevents unnecessary style computation when not specifying numeric size. Also will cache font size calculation in the html attr after first check. This improves average render time by 3x

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-03-05 22:38 UTC, mathisscott requested changes

2021-03-05 22:38 UTC, mathisscott commented on packages/core/src/icon/utils/icon.classnames.ts
> +      const val = pxToRem(parseInt(size));
Might need to move `val` into a `let` on line 36 and then assign it to `val` here.

2021-03-05 22:38 UTC, mathisscott commented on packages/core/src/internal/utils/css.spec.ts
> +    it('should cache the rem calculation to the HTML cds-font-size attr', () => {
👍

2021-03-05 22:38 UTC, mathisscott commented on packages/core/src/internal/utils/css.ts
> +  let base = parseInt(document.documentElement.getAttribute('cds-base-font') as any);
Would this attribute really comeback as `any`? Seems like it would be either a `string | undefined | null`.

2021-03-08 16:02 UTC, mathisscott approved these changes

2021-03-08 16:02 UTC, mathisscott commented on packages/core/src/icon/utils/icon.classnames.ts
> +      val = pxToRem(parseInt(size)); // set val in block to run expensive call only when needed
🏆

2021-03-10 19:52 UTC, hippee-lee approved these changes

2021-03-10 21:13 UTC, merged