feat(button): use bright colors on dark theme
vmware/clarity pull request #5857
Opened 2021-04-15 20:28 UTC by astorije

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Light theme | Dark theme
--- | ---
<img width="527" alt="Screen Shot 2021-04-15 at 10 21 19 PM" src="https://user-images.githubusercontent.com/113730/114933957-f9721c00-9e41-11eb-8a9a-973f857ffa56.png"> | <img width="517" alt="Screen Shot 2021-04-15 at 10 21 32 PM" src="https://user-images.githubusercontent.com/113730/114933962-faa34900-9e41-11eb-945c-3fbabaa94de7.png">

Issue Number: https://github.com/vmware/clarity/issues/5851

## What is the new behavior?

Light theme | Dark theme
--- | ---
<img width="310" alt="Screen Shot 2021-04-15 at 10 22 03 PM" src="https://user-images.githubusercontent.com/113730/114934024-0d1d8280-9e42-11eb-895a-ae8725b726fe.png"> | <img width="283" alt="Screen Shot 2021-04-15 at 10 22 11 PM" src="https://user-images.githubusercontent.com/113730/114934030-0db61900-9e42-11eb-9242-5bbfd353bc48.png">
<img width="299" alt="Screen Shot 2021-04-15 at 10 22 33 PM" src="https://user-images.githubusercontent.com/113730/114934032-0e4eaf80-9e42-11eb-92bc-e2e1b53dbb56.png"> | <img width="282" alt="Screen Shot 2021-04-15 at 10 22 50 PM" src="https://user-images.githubusercontent.com/113730/114934036-0f7fdc80-9e42-11eb-8e1f-c42ea1a131ac.png">
<img width="1040" alt="Screen Shot 2021-04-15 at 10 24 32 PM" src="https://user-images.githubusercontent.com/113730/114934040-10187300-9e42-11eb-9fac-93eca26ea0c0.png"> | <img width="1025" alt="Screen Shot 2021-04-15 at 10 24 41 PM" src="https://user-images.githubusercontent.com/113730/114934042-10b10980-9e42-11eb-9934-8f8984915a47.png">

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

Inverse buttons in dark themes will now have the opposite colors as previously.

2021-04-15 21:15 UTC, mathisscott requested changes

2021-04-15 21:15 UTC, mathisscott commented on packages/core/src/button/base-button.element.scss
> +  --color: #{$cds-global-color-white};
Putting a hold on this for now until we can talk through implications discussed in #5851

2021-06-08 17:08 UTC, hippee-lee commented
@astorije or @mathisscott - any updates here? Is there a resolution or path forward for this PR? If not I'd like to close this for now.

2021-06-08 17:34 UTC, mathisscott commented
Given that the neutral button was introduced in #5859 , it seems like we can leave the inverse variant as a true inverse. The issue here can now be solved by using the neutral button in dark theme.

@astorije , does that sound reasonable to you?

2021-06-08 18:32 UTC, astorije commented
As we discussed on Zoom last time, the neutral button I added was unrelated as it doesn't support this use case. We cannot use it for the screenshots posted at https://github.com/vmware/clarity/issues/5851.

I still think this PR is relevant and corresponds to a more real-world / practical usage of the inverse variant, but it's obviously up to you. If you think this can still be considered, I am more than happy to fix the PR conflict or update the PR to your liking. If not, we will keep our current implementation, i.e. inverse variant with CSS token overrides, though I was hoping to be able to use it without overrides like we try to do everywhere we can 🙏

2021-06-08 21:07 UTC, hippee-lee commented
Ok, thanks for the input. It sounds like we are leaving the inverse tokens as they were. I'll close this for now unless something changes.

2021-06-08 21:07 UTC, closed without merging

2021-06-08 21:08 UTC, astorije commented
Alright then 😢
Thanks for going through this ticket with me!