fix: empty value boolean properties in @cds/angular
vmware/clarity pull request #5932
Opened 2021-05-07 06:41 UTC by Shijir

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #5916 

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-05-07 13:26 UTC, mathisscott requested changes

2021-05-07 13:26 UTC, mathisscott commented on apps/core-angular-cli/src/app/app.component.ts
> +  expandedChange(event: any): void {
I don't think this needs to be an `any` type. `CustomEvent` should work here as the type.

2021-05-07 21:50 UTC, mathisscott approved these changes

2021-05-07 21:52 UTC, Shijir commented on apps/core-angular-cli/src/app/app.component.ts
> +  expandedChange(event: any): void {
Gotcha. I've made use of it in the event emitter types.

2021-05-12 07:40 UTC, bbogdanov approved these changes

2021-05-14 15:29 UTC, merged