fix: accordion and stepper issue with clrAccordionPanelOpenChange event
vmware/clarity pull request #6013
Opened 2021-05-31 14:57 UTC by bdryanovski

Fixing issue #5957 with not firing both states of the clrAccordionPanelOpenChange (true and false)

Also closing #5981 - could not reproduce it - probably fixed in previous versions (tested with latest v5)

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #5981 & #5957 

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

closes #5957 
closes #5981

2021-06-01 18:03 UTC, Jinnie approved these changes

2021-06-08 21:33 UTC, hippee-lee requested changes
This lgtm. Before I give it a :shipit: I'd like to see a test that covers the change so we know if 
```this.panelOpen``` 
stops staying in sync with 
```panel.open```

2021-06-09 15:51 UTC, bdryanovski commented
@hippee-lee done.

In addition to that will try to explain the case here for historical reasons.

Because we use the `BehaviorSubject` we have a bit strange result that the `(clrAccordionPanelOpenChange)` is called when the Accordion is rendering for the first time with its initial value. And that is creating an unneeded event - also for some reason that I could not found out is that I could not use RxJs mechanics for preventing emitting an event only when changed - Previous and Next values for some strange reasons are already the same.

To NOT create additional private property to track internally the state of the Accordion and decide to emit or not an event - I'm using the `panelOpen` as a reference point to the previous value. 

But when there is no Angular binding to it - it goes off sync (we no longer go into `ngOnChanges`) so this is the reason for manually assigning it into the emitter method.

In addition to that, the `panelOpen` is used only into the `ngOnInit` to set the value and to be outside property to trigger change - when it comes to the template we use only `panel.open` - so no side effects into the template could be expected.

Trying to go back and fix the root of the problem `BehaviorSubject` - I'm getting a lot of lifecycle errors when it comes to rendering it. Really really hard to debug it. Also any changes made to the Accordion have effect on the Stepper and until someone decide to rework both of them - I think that this patch version is good enough for the moment

2021-06-09 16:17 UTC, hippee-lee approved these changes

2021-06-10 11:25 UTC, merged