website-card-page
vmware/clarity pull request #6022
Opened 2021-06-03 12:13 UTC by bbogdanov

Adding `cds-card` documentation in the website

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2021-06-03 13:01 UTC, mathisscott approved these changes
Make sure @colinreedmiller or @yuxin-ux get to check this out.

2021-06-04 17:41 UTC, hippee-lee requested changes

2021-06-04 17:41 UTC, hippee-lee commented on apps/website/.vuepress/theme/global-components/CdsDemos.vue
> +      <h2 cds-layout="m-b:md">{{ story.storyName | uppercaseSplit }}</h2>
👍🏼

2021-06-04 17:41 UTC, hippee-lee commented on apps/website/core-components/card/README.md
> +Cards are used to apply a container around a related grouping of information.
markdown content should be wrapped inside of the appropriate blocks to apply the correct core spacing tokens to the generated content. 
E.g:

``` markdown
::: component-summary
Summary of the component goes here.
:::
```

The same goes for the various level headings and associated description. Any one of the existing core-component md files should be following this pattern.

2021-06-08 17:31 UTC, hippee-lee reviewed
lgtm 👍🏼

2021-06-08 17:31 UTC, hippee-lee approved these changes

2021-06-11 11:24 UTC, merged

2021-06-11 11:26 UTC, bbogdanov commented
#5785

2021-06-11 11:27 UTC, bbogdanov commented
#5563