feat: adoption guide update by adding more pages and fixes
vmware/clarity pull request #6119
Opened 2021-07-05 11:42 UTC by bdryanovski

* fixing broken snippets
 * making code example in side-by-side mode
 * adding pages based on the eslint list
 * adding not-ready component to mark the pages (needs more work)

2021-07-05 11:55 UTC, bbogdanov approved these changes
`feat(adoption): adding pages for all available components`

The fixes are not mandatory so I guess we can skip them in the title

2021-07-05 12:09 UTC, Jinnie requested changes
Good progress!

Only a couple of typo fixes from me in this review.

2021-07-05 12:09 UTC, Jinnie commented on apps/adoption/src/app/pages/getting-started.page.ts
> +    <h3>For who is this guide?</h3>
Who is this guide for

2021-07-05 12:09 UTC, Jinnie commented on apps/adoption/src/app/pages/getting-started.page.ts
> +      This guide is for everyone that want and needs to adopt our new Core components into there existing Clarity
...that wants and needs....  ... into their existing....

2021-07-05 12:09 UTC, Jinnie commented on apps/adoption/src/app/pages/getting-started.page.ts
> +      Angular application. It's design to help you rework and adopt in the best way and still get the same result as
It's designed to.....

2021-07-05 12:09 UTC, Jinnie commented on apps/adoption/src/app/pages/getting-started.page.ts
> +      The guide is structure into sections, every section will provide examples based on our Angular components and
...is structured...

2021-07-05 12:09 UTC, Jinnie commented on apps/adoption/src/app/pages/getting-started.page.ts
> +      there Core counterparts. Into the form of guides, snippets and corner cases that will help you with the adoption
... their Core counterparts.

2021-07-05 12:40 UTC, Jinnie approved these changes
Thank you!

2021-07-06 07:42 UTC, bbogdanov commented
I know it might get tedious and I am sorry about it. 

`feat(adoption): createing pages structure`  -> `feat(adoption): creating pages structure` 

The additional `e` is the change.

2021-07-06 13:43 UTC, merged