chore(core): update normalize css recommendation
vmware/clarity pull request #6128
Opened 2021-07-07 13:57 UTC by coryrylan

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Core currently uses [normalize.css](https://github.com/necolas/normalize.css) for normalizing browser inconsistencies. However the project has become mostly inactive from updates and has legacy ie11/10 styles we no longer need.

## What is the new behavior?
Update the default recommendation to use the [modern-normalize](https://github.com/sindresorhus/modern-normalize) package. This is better maintained and drops the IE dependencies. I'll have a follow up PR to update demo apps as they need most of their dependencies updated at some point. 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-07-07 17:06 UTC, mathisscott requested changes
Do we need to update this in `@cds/react` or `@cds/angular`?

2021-07-07 17:13 UTC, coryrylan commented
> Do we need to update this in `@cds/react` or `@cds/angular`?

Yeah I forgot we list it as an optional dependency in those. I have to patch the website as well. I missed a reference so the website isnt building properly.

2021-07-19 23:11 UTC, mathisscott approved these changes

2021-07-19 23:33 UTC, hippee-lee approved these changes

2021-07-20 14:38 UTC, merged