feat(core:icon): adding vol 20 of icons
vmware/clarity pull request #6270
Opened 2021-08-19 16:31 UTC by bdryanovski

Icons for Vol 20 #5883

<img width="894" alt="Screenshot 2021-08-19 at 19 29 41" src="https://user-images.githubusercontent.com/204564/130107076-92bdfa18-0af8-4ae7-9969-b8afd52531bf.png">

<img width="905" alt="Screenshot 2021-08-19 at 19 30 15" src="https://user-images.githubusercontent.com/204564/130107170-08f3818c-e8f5-4dab-ad71-95884c27c8d2.png">

2021-08-19 17:25 UTC, mathisscott approved these changes

2021-08-19 17:27 UTC, bbogdanov approved these changes

2021-08-19 17:28 UTC, mathisscott requested changes
These icons should be added to `packages/core/web-dev-server.config.js` and also to `apps/website/data/icon-inventory.js`

Otherwise, 👍

2021-08-25 12:41 UTC, mathisscott approved these changes

2021-08-26 17:13 UTC, merged