fix: use variable for table header color
vmware/clarity pull request #6285
Opened 2021-08-23 17:05 UTC by Shijir

Signed-off-by: stsogoo <stsogoo@vmware.com>

In this PR, we are using the correct color variable for `--clr-thead-color`, which is `$clr-thead-color`. Also, `$clr-thead-color` is added to `_theme.dark.clarity.scss` so that users could set it to their desired value.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: https://github.com/vmware/clarity/issues/6276

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2021-08-23 17:47 UTC, mathisscott approved these changes

2021-08-23 18:52 UTC, bbogdanov approved these changes

2021-08-23 18:54 UTC, bbogdanov requested changes
Please fix the commit message

`fix(angular:table): use variable for table header color`

2021-08-24 16:23 UTC, bbogdanov approved these changes

2021-09-02 16:05 UTC, merged