feat(react:panel): panel wrapper
vmware/clarity pull request #6296
Opened 2021-08-26 16:07 UTC by bbogdanov

Signed-off-by: Bogdan Bogdanov <bbogdanov@vmware.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-08-26 16:45 UTC, hippee-lee approved these changes

2021-08-30 14:23 UTC, coryrylan requested changes

2021-08-30 14:23 UTC, coryrylan commented on packages/react/src/panel/package.json
> +    "name": "@cds/react/internal/visual-checkbox"
Looks like this should be `@cds/react/internal/panel`

2021-09-01 16:31 UTC, mathisscott approved these changes

2021-09-02 14:03 UTC, coryrylan approved these changes

2021-09-03 07:38 UTC, merged