fix(core:styles): cleanup focus css prop
vmware/clarity pull request #6396
Opened 2021-10-11 18:57 UTC by coryrylan

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the new behavior?
This is some work I am pulling out of the datagrid branch. This adds the native focus outline as a token value to help make the outline usage consistent within components. This also adds a focus outline state demo for the interaction examples in storybook. 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-10-11 19:00 UTC, coryrylan commented on packages/core/src/button/button.element.ts
> +  static styles = [baseStyles, styles];
I combined base button styles and the buttons styles int a single style sheet. Icon button inherits button styles from the button element.

2021-10-11 19:01 UTC, coryrylan commented on packages/core/src/button/icon-button.element.ts
> +  }
Rather than generate the base button css twice just inherit from the button

2021-10-11 19:03 UTC, coryrylan commented on packages/core/src/forms/control-inline/control-inline.element.scss
> +}
This ensures the inline controls (checkbox, radio, switch) get the appropriate standard focus outline and minimum touch target size

2021-10-11 19:06 UTC, coryrylan commented on packages/core/src/forms/control-inline/control-inline.element.ts
> +          <div role="presentation" focusable @click=${this.selectInput}></div>
This fixes an a11y bug where the SR can get confused on treating the click handler as an interactive group rather than focusing to the native slotted checkbox or radio input.

2021-10-11 19:19 UTC, coryrylan commented on packages/core/src/forms/control-inline/control-inline.element.scss
> +  --cds-alias-object-interaction-touch-target: #{$cds-global-space-8};
Sets a minimum touch target for inline elements like radio/checkbox. Also useful for datagrid to align target/focus to cell easily.

2021-10-11 19:21 UTC, coryrylan commented on packages/core/src/input/input.element.scss
> +  --cds-alias-object-interaction-outline-offset: 0;
Input overrides the default outline since it uses the underline focus effect. However I still use the variable so its consistent with theming and can be adjusted like any other component.

2021-10-12 03:32 UTC, mathisscott requested changes

2021-10-12 03:32 UTC, mathisscott commented on packages/core/src/button/base-button.element.scss
> -// Copyright (c) 2016-2021 VMware, Inc. All Rights Reserved.
Why are we deleting base button?

2021-10-12 04:06 UTC, coryrylan commented on packages/core/src/button/base-button.element.scss
> -// Copyright (c) 2016-2021 VMware, Inc. All Rights Reserved.
See:
https://github.com/vmware/clarity/pull/6396#discussion_r726506590
https://github.com/vmware/clarity/pull/6396#discussion_r726506969

2021-10-12 20:14 UTC, Shijir commented on packages/core/src/accordion/accordion-panel.element.ts
> +        focusable
Would this `focusable` attribute work in React when users need to assign boolean values?

2021-10-12 20:15 UTC, Shijir commented on packages/core/src/forms/control-inline/control-inline.element.scss
> +[focusable] {
Related question. I remember for boolean attributes, I needed to specify `[focusable]=true/false` in React. I wonder if that applies here too.

2021-10-12 21:07 UTC, coryrylan commented on packages/core/src/accordion/accordion-panel.element.ts
> +        focusable
This in particular is internal in the shadow dom so no consumer would access/use it. It is for making it easy to apply the focus element styles internal to our templates.

2021-10-12 21:10 UTC, coryrylan commented on packages/core/src/forms/control-inline/control-inline.element.scss
> +[focusable] {
Same as the other example, this is internal to the template. It doesnt use`::slotted` so its not applying as part of the public API. If its a property of the component React can set it like any other property however if its a plain html attribute (`@property` was not used in the web component) then users will run into this problem https://github.com/facebook/react/issues/9230

2021-10-12 21:31 UTC, Shijir approved these changes

2021-10-12 21:32 UTC, Shijir commented on packages/core/src/forms/control-inline/control-inline.element.scss
> +[focusable] {
Makes sense. Thanks for the explanation.

2021-10-12 21:45 UTC, mathisscott commented on packages/core/src/button/base-button.element.scss
> -// Copyright (c) 2016-2021 VMware, Inc. All Rights Reserved.
Got it. I was confused. I thought we were deleting `base-button.element.ts`...

2021-10-12 21:45 UTC, mathisscott approved these changes

2021-10-12 23:32 UTC, merged