feat(core:forms): add CdsRadioPanel and CdsCheckboxPanel
vmware/clarity pull request #6409
Opened 2021-10-15 01:12 UTC by hippee-lee

This is the addition of two new form components. They are an extension
of the CdsRadio and CdsCheckbox with css on top to allow for more room
in the label to project content.

Signed-off-by: Matt Hippely <mhippely@vmware.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features) -> Storybook docs for beta components
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?
This is a feature changeset that adds tw onew components:

- CdsRadioPanel - a single select form component that allows for more content to be projected into the label
- CdsCheckboxPanel - a multi-select form component that allows for more content to be projected into the label
- 

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
n/x

Issue Number: #4908

## What is the new behavior?
There are two new components that have been evolved with the original github issue noted above. 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-10-18 11:56 UTC, bbogdanov approved these changes
Awesome!

2021-10-18 15:29 UTC, hippee-lee commented on packages/core/build/tokens.ts
> +      dark: token(color.red[900]),
Added to provide a dark theme variation of the theme-able danger hover color.

2021-10-18 15:30 UTC, hippee-lee commented on packages/core/rollup.config.js
> +      './src/selection-panels',
Part of a `fix || hack` to let the selectable panel components build with the current `@cds/angular` script. It bundles the directives into a selectable panels module. 

See [here](https://github.com/vmware/clarity/pull/6409/files#diff-68422baf4507d4db7ef740b6377b4cdd118f6d7455b9ef3cd963a6db3a4d222dR7) also.

2021-10-18 15:34 UTC, hippee-lee commented on packages/core/src/selection-panels/index.ts
> +export * from './checkbox/checkbox-panel.element.js';
Added as as a `fix || hack` to let the selectable panel components build with the current `@cds/angular` script. It bundles the directives into a selectable panels module. 

See [here](https://github.com/vmware/clarity/pull/6409/files#diff-2f784764604720e8134392c8d17d6a3f1097255ce2243fc1c5ef16cf9f39452aR61) also.

2021-10-18 15:36 UTC, hippee-lee commented on packages/core/src/checkbox/checkbox.element.scss
> +
I need to undo these changes. They are vestigial from the first version where styles are added to the existing checkbox/radio component.

2021-10-18 15:36 UTC, hippee-lee commented on packages/core/src/radio/radio.element.scss
> +  --complex-sm-size: calc(#{$cds-global-space-8} * 10); // 180
Need to undo these changes.

2021-10-18 15:37 UTC, hippee-lee commented on packages/core/src/selection-panels/shared/selection-panel.element.scss
> +@import './../../styles/tokens/generated/index';
Share css for both radio and checkboxes from this file.

2021-10-18 17:55 UTC, coryrylan commented on packages/react/src/checkbox-panel/entrypoint.tsconfig.json
> +{
Could the React components follow the same folder structure as the core library so the imports are the same?

```
/packages/react
  /selection-panels
    /checkbox
    /radio
```


```tsx
import { CdsCheckboxPanel } from '@cds/core/selection-panels/checkbox';
import { CdsCheckboxPanel } from '@cds/react/selection-panels/checkbox';
```

2021-10-18 18:41 UTC, hippee-lee commented on packages/react/src/checkbox-panel/entrypoint.tsconfig.json
> +{
Yes, I'll update the PR.

2021-10-18 20:47 UTC, coryrylan commented on packages/core/src/selection-panels/index.ts
> +export * from './checkbox/checkbox-panel.element.js';
We should mark these exports with a `@private` comment in this file so teams don't use this and use the component import directly. That way we can fix the underlying issue with the `@cds/angular` generator supporting components in nested directories. 

```javascript
import '@cds/core/selection-panels/checkbox/register.js';
```

2021-10-20 16:41 UTC, coryrylan requested changes

2021-10-20 16:41 UTC, coryrylan commented on packages/core/src/checkbox/checkbox.stories.ts
> +        <cds-checkbox selection-panel>
Is this leftover from a different API? Doesnt seem to be directly used anywhere

2021-10-20 16:41 UTC, coryrylan commented on packages/core/src/radio/radio.stories.ts
> +        <cds-radio selection-panel>
Is this leftover from a different API? Doesnt seem to be directly used anywhere

2021-10-20 16:41 UTC, coryrylan commented on packages/core/src/radio/radio-group.element.ts
> +  @querySlotAll('cds-radio, cds-complex-radio') protected controls: NodeListOf<CdsRadio>;
Should this be `cds-radio-panel` rather than `cds-complex-radio`? I think this is causing the radios to not have an associated `name` attr breaking the group https://616e01a57945d551c1e1dd72--vmware-clarity.netlify.app/storybook/core/index.html?path=/story/stories-radio-panel--basic

2021-10-20 16:41 UTC, coryrylan commented on packages/core/src/selection-panels/shared/selection-panel.element.scss
> +:host .private-host {
`:host` is inferred automatically so you can omit it here

2021-10-20 16:41 UTC, coryrylan commented on packages/core/src/selection-panels/shared/selection-panel.element.scss
> +:host ::slotted(label) {
`:host` is inferred automatically so you can omit it here

2021-10-20 16:41 UTC, coryrylan commented on packages/core/src/selection-panels/shared/selection-panel.element.scss
> +  --lbl-background: #{$cds-alias-object-interaction-background}; // naming conflict with inherited --background
Maybe instead of `--lbl-*` we could do `--panel-*`?

2021-10-20 16:41 UTC, coryrylan commented on packages/core/src/selection-panels/shared/selection-panel.element.scss
> +}
The focus outline is not positioned around the the checkbox/radio. I think replacing this .input block with the following should fix it

```scss
.input,
[focusable] {
  z-index: 99;
  position: absolute;
  right: #{$cds-global-space-4};
  top: #{$cds-global-space-4};
  left: initial;
  margin: 0 0 #{$cds-global-layout-space-sm} #{$cds-global-layout-space-xs};
}
```

2021-10-20 16:41 UTC, coryrylan commented on packages/core/src/selection-panels/shared/selection-panel.element.scss
> +  --lbl-height: var(--xl-size);
I think we could simplify the CSS custom prop API by providing a `--panel-width` and `--panel-height` property and drop the size css custom properties. It will still let teams customize existing sizes and custom ones as well

```scss
:host([size='lg']) ::slotted(label) {
  --panel-width: calc(#{$cds-global-space-8} * 20);
  --panel-height: calc(#{$cds-global-space-8} * 20);
}
```

```scss
// consumer app styles
cds-checkbox-panel[size='lg'] {
  --panel-width: 480px;
  --panel-height: 480px;
}

cds-checkbox-panel.product-jumbo {
  --panel-width: 980px;
  --panel-height: 980px;
}
```

This would align closer to some of our existing size based APIs
https://github.com/vmware/clarity/blob/next/packages/core/src/modal/modal.element.scss#L16 
https://github.com/vmware/clarity/blob/next/packages/core/src/progress-circle/progress-circle.element.scss#L38 
https://clarity.design/storybook/core/?path=/story/internal-documentation-templates-and-styles--page

2021-10-20 17:31 UTC, hippee-lee commented on packages/core/src/checkbox/checkbox.stories.ts
> +        <cds-checkbox selection-panel>
yeah, I was using the attr in the OG code that lived directly on the CdsCheckbox component. Then I used search and replace and I missed it when applying the changes. I'll remove.

2021-10-20 17:32 UTC, hippee-lee commented on packages/core/src/radio/radio.stories.ts
> +        <cds-radio selection-panel>
Same answer as before. I will remove.

2021-10-20 17:33 UTC, hippee-lee commented on packages/core/src/radio/radio-group.element.ts
> +  @querySlotAll('cds-radio, cds-complex-radio') protected controls: NodeListOf<CdsRadio>;
yeah, I forgot about this query. I'll update it.

2021-10-20 20:05 UTC, coryrylan commented on packages/core/src/selection-panels/radio/radio-panel.element.ts
> +import { SelectionPanelSizes } from '@cds/core/selection-panels/shared/selection-panel.interfaces';
I think this will cause a circular dependency referring to its own entrypoint, the path should be relative

```typescript
import { SelectionPanelSizes } from '../shared/selection-panel.interfaces.js';
```

2021-10-20 20:05 UTC, coryrylan commented on packages/core/src/selection-panels/radio/radio-panel.element.ts
> +  @property({ type: String, reflect: true })
nit: reflect is true by default for `@property` so its not needed

2021-10-20 20:05 UTC, coryrylan commented on packages/core/src/selection-panels/checkbox/checkbox-panel.element.ts
> +  @property({ type: String, reflect: true })
nit: reflect is true by default for `@property` so its not needed

2021-10-20 20:05 UTC, coryrylan commented on packages/core/src/selection-panels/checkbox/checkbox-panel.stories.mdx
> +import '@cds/core/selection-panels/radio/checkbox/register.js';
Path

```javascript
import '@cds/core/selection-panels/checkbox/register.js';
```

2021-10-20 20:05 UTC, coryrylan commented on packages/core/src/selection-panels/radio/radio-panel.element.ts
> + *   <input type="checkbox" />
`type="panel"`

2021-10-20 20:05 UTC, coryrylan commented on packages/core/src/selection-panels/radio/radio-panel.stories.mdx
> +</cds-radio-panel>
For the example here should we add another radio and put it in a group?

2021-10-21 01:39 UTC, coryrylan approved these changes

2021-10-21 16:26 UTC, merged