docs/fix bad links
vmware/clarity pull request #6427
Opened 2021-10-22 04:57 UTC by steve-haar

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

some documentation links in markdown files were broken

Issue Number: N/A

## What is the new behavior?

links should now work properly

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-10-22 07:43 UTC, bdryanovski approved these changes
LGTM

2021-10-22 14:33 UTC, coryrylan requested changes

2021-10-22 14:33 UTC, coryrylan commented on .github/ISSUE_TEMPLATE/contribution-proposal.md
> +_Please review our [Contribution guide](/docs/CONTRIBUTING.md) for more details about how to contribute effectively._
This one does need to be updated but should be updated to use `next` in the full path
`https://github.com/vmware/clarity/blob/next/docs/CONTRIBUTING.md`

2021-10-22 14:33 UTC, coryrylan commented on apps/website/angular-components/accordion/README.md
> +Accordions are a collection of panels that encapsulate a title and content. You can read more about [ClrAccordionTitle](/apps/website/angular-components/accordion/api.md/#clraccordiontitle) and [ClrA
These website paths are correct, the urls are relative to the hosted website not the local files. You can see the website build preview from the CI here

https://617249549be3dd9858aa59d4--vmware-clarity.netlify.app

https://github.com/vmware/clarity/pull/6427/checks

2021-10-22 14:33 UTC, coryrylan commented on apps/website/angular-components/accordion/api.md
> +ClrAccordionPanel is a child of [ClrAccordion](./api.md/#clraccordion)
The `.md` should be omitted as it breaks the url path
https://617249549be3dd9858aa59d4--vmware-clarity.netlify.app/angular-components/accordion/api.md/#clraccordion
https://clarity.design/angular-components/accordion/api/#clraccordion

2021-10-22 14:36 UTC, coryrylan commented on apps/website/angular-components/accordion/api.md
> +ClrAccordionContent is a child of [ClrAccordionPanel](#clraccordionpanel)
These paths seem to work fine in either format

https://617249549be3dd9858aa59d4--vmware-clarity.netlify.app/angular-components/accordion/api/
https://clarity.design/angular-components/accordion/api/

2021-10-23 01:07 UTC, steve-haar commented on .github/ISSUE_TEMPLATE/contribution-proposal.md
> +_Please review our [Contribution guide](/docs/CONTRIBUTING.md) for more details about how to contribute effectively._
Sorry, I corrected the URL to be fully qualified and not just a relative path as you suggested.

2021-10-23 01:10 UTC, steve-haar commented on apps/website/angular-components/accordion/README.md
> +Accordions are a collection of panels that encapsulate a title and content. You can read more about [ClrAccordionTitle](/apps/website/angular-components/accordion/api.md/#clraccordiontitle) and [ClrA
I'm sorry, I was clicking around in the links in GitHub and they appeared to be broken. I realize now that these markdown files are deployed as a website and making these changes would break the website. I removed this commit from the PR.

2021-10-23 01:10 UTC, steve-haar commented on apps/website/angular-components/accordion/api.md
> +ClrAccordionPanel is a child of [ClrAccordion](./api.md/#clraccordion)
I'm sorry, I was clicking around in the links in GitHub and they appeared to be broken. I realize now that these markdown files are deployed as a website and making these changes would break the website. I removed this commit from the PR.

2021-10-23 01:10 UTC, steve-haar commented on apps/website/angular-components/accordion/api.md
> +ClrAccordionContent is a child of [ClrAccordionPanel](#clraccordionpanel)
I'm sorry, I was clicking around in the links in GitHub and they appeared to be broken. I realize now that these markdown files are deployed as a website and making these changes would break the website. I removed this commit from the PR.

2021-10-26 00:39 UTC, coryrylan approved these changes

2021-10-26 00:40 UTC, merged