fix: only focus on modal body if scrollable
vmware/clarity pull request #6546
Opened 2022-01-04 21:09 UTC by steve-haar

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
A modal body will always have a tab index, even if the body is not scrollable.

Issue Number: N/A
closes https://github.com/vmware/clarity/pull/6493

## What is the new behavior?
A modal body should only have a tab index if the content is tall enough to make the body scrollable. If the content is not tall enough, then the modal body is not operable and should not have a tab index. 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-01-04 21:15 UTC, mathisscott requested changes

2022-01-04 21:15 UTC, mathisscott commented on projects/angular/src/modal/modal-body.spec.ts
> +    resizeObserverCallback();
What are the repeated `resizeObserverCallback()` executions doing?

2022-01-04 21:17 UTC, steve-haar commented on projects/angular/src/modal/modal-body.spec.ts
> +    resizeObserverCallback();
Sorry, I just added a comment to the code right as you were reviewing this. There is an issue with ResizeObservable not working with angular tests: https://github.com/angular/angular/issues/31695#issuecomment-507832750. This was the only workaround I could find. Using fakeAsync/tick does not seem to work.

2022-01-04 21:18 UTC, mathisscott commented on projects/angular/src/modal/modal-body.spec.ts
> +    resizeObserverCallback();
Got it. Thanks for the clarification!

2022-01-04 21:19 UTC, mathisscott approved these changes

2022-01-06 15:15 UTC, coryrylan approved these changes

2022-01-07 16:58 UTC, merged